// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMV_Final.Models
{
    public partial class Driver
    {
        public Driver()
        {
            DriverVehicles = new HashSet<DriverVehicle>();
        }

        public string DriverId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int SocialSecurity { get; set; }

        public virtual ICollection<DriverVehicle> DriverVehicles { get; set; }
    }
}