// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMV_Final.Models
{
    public partial class DriverVehicle
    {
        public string DriverId { get; set; }
        public string VehicleId { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}