// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMV_Final.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            DriverVehicles = new HashSet<DriverVehicle>();
        }

        public string VehicleId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int PlateNumber { get; set; }

        public virtual ICollection<DriverVehicle> DriverVehicles { get; set; }
    }
}